chronograf:
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    tls: true
    secretName: chronograf-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hostname: chronograf.sievert.fun
  persistence:
    enabled: true
    size: 1Gi
